- hosts: localhost
  become: false

  tasks:
    - name: Remove old container
      shell: docker rm -f poc7-container || true
      ignore_errors: yes

    - name: Pull latest image
      shell: docker pull kurukuntlacharan9170/poc-7:latest

    - name: Run container
      shell: docker run -d -p 8083:80 --name poc7-container kurukuntlacharan9170/poc-7:latest
